"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


from pathlib import Path
import os
import json
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# 경로를 찾아가는 다른 방법 : BASE_DIR/.config_secret
CONFIG_SECRET_DIR = os.path.join(BASE_DIR,'.config_secret')
BASE_JSON = os.path.join(CONFIG_SECRET_DIR,'base.json')
base_file = json.loads(open(BASE_JSON).read())

print(CONFIG_SECRET_DIR,"&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = base_file['secret_key']\

# 위의 코드는 SECRET_KEY를 밖에있는 config 폴더로 빼주었기때문에 
#해당 파일로 가서 SECRET_KEY를 분리해 오는 code입니다.
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 
# SECURITY WARNING: don't run with debug turned on in production!


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  #현재 우리 사이트 관련된 정보를 다루기 위해서 추가해줬습니다.
    
    #Django 소셜 로그인 관련 App
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    
    #카카오(다른 서비스의 소셜로그인 사용시 다른 서비스 등록해줘야함.)
    'allauth.socialaccount.providers.kakao',

    'memo',
    'accounts',

    #텍스트 에디터
    'django_summernote',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ko' #프로젝트의 언어셋팅을 한글로 바꿉니다.

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/' #사용자가 STATIC파일을 요청할 URL
STATIC_ROOT = BASE_DIR / 'static' #앱별로 흩어진 Static파일들을 해당 경로에 모아줌(python manage.py collectstatic)
# 사용자는 STATIC_URL의 경로로 요청하게되고 우리는 그 장소에 static 요소들을 준비해둔다. 
# 그래서 STATIC_URL 이랑 STATIC_ROOT의 위치는 일치시켜주자.
# 개발할때는 runserver 명령어 실행시 내부적으로 collectstatic와 같은 동작을 수행함.
# 따라서 STATIC_ROOT는 개발시에는 굳이 필요없지만 나중에 배포시에는 runserver명령어를 실행할게 아니므로, 명시적으로 collectstatic을 해줘야하고
# 이를 위해서 STATIC_ROOT도 작성해줘야한다.

STATICFILES_DIRS = [
    BASE_DIR / "basestatic",
]
# 프로젝트 폴더 밑에 basestatic이라는 폴더를 하나 만들어주고 base.css를 추가적으로 작성해서 관리하고있습니다.
# 해당 폴더는 새로 만들어 준 폴더이므로 STATIC_FILE을 관리하는 FINDER가 해당 폴더도 인지하고 모아줄 수 있게 등록을 해주는 과정입니다.

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 여기서 BASE_DIR은 프로젝트 폴더를 의미합니다.

LOGIN_REDIRECT_URL = '/' #로그인 후 REDIRECT경로를 설정하는데
                         #따로 설정하지 않으면 Profile페이지를 찾아갑니다.
LOGOUT_REDIRECT_URL = '/'


AUTHENTICATION_BACKENDS = [

    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',

]
#기존 Django model과의 호환을 위해서 설정해준다.



SITE_ID = 1   #admin page에서 '사이트틀' 부분에서 example.com을 수정해서 우리의 domain주소로 바꿔 줬기때문에
              #SITE_ID가 1번이고, 만약에 admin site에서 사이트틀 내부의 정보를 지우고 추가 생성해준거라면 추가생성한 정보의 ID값과 일치시켜줘야한다.


#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
#아래는 summernote와 관련된 추가 설정입니다.
X_FRAME_OPTIONS = 'SAMEORIGIN'

SUMMERNOTE_CONFIG = {
    # Using SummernoteWidget - iframe mode, default
    'iframe': True,

    # Or, you can set it to `False` to use SummernoteInplaceWidget by default - no iframe mode
    # In this case, you have to load Bootstrap/jQuery sources and dependencies manually.
    # Use this when you're already using Bootstrap/jQuery based themes.
    'iframe': False,

    # You can put custom Summernote settings
    'summernote': {
        # As an example, using Summernote Air-mode
        'airMode': False,

        # Change editor size
        'width': '480',
        'height': '300',

        # Use proper language setting automatically (default)
        'lang': None,
        
        # Toolbar customization
        # https://summernote.org/deep-dive/#custom-toolbar-popover
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['fontname', ['fontname']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']],
        ],

        # Or, explicitly set language/locale for editor
        'lang': 'ko-KR',
    }
}
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

